# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlogin', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='profile.jpg', upload_to='image/'),
            preserve_default=False,
        ),
    ]
