# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import studentlogin.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlogin', '0003_auto_20171115_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignment',
            field=models.FileField(default='sample.pdf', upload_to=studentlogin.models.get_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to=studentlogin.models.get_path),
        ),
    ]
